# Generated by Django 5.2.3 on 2025-06-16 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва виробника')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Країна')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рік заснування')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
            ],
        ),
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва гітари')),
                ('body_type', models.CharField(choices=[('ST', 'Stratocaster'), ('LP', 'Les Paul'), ('TE', 'Telecaster'), ('SG', 'SG'), ('EX', 'Explorer')], default='ST', max_length=2, verbose_name='Тип корпусу')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('available', models.BooleanField(default=True, verbose_name='В наявності')),
                ('color', models.CharField(default='Black', max_length=50, verbose_name='Колір')),
                ('stock', models.PositiveIntegerField(default=10, verbose_name='Кількість на складі')),
                ('added', models.DateField(auto_now_add=True, verbose_name='Дата додавання')),
                ('description', models.TextField(blank=True, help_text='Короткий опис товару', verbose_name='Опис')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.manufacturer', verbose_name='Виробник')),
            ],
        ),
    ]
